pam_faildelay: fix compilation warnings on 32bit platforms
Fix the following warning reported by gcc on 32bit platforms:

  pam_faildelay.c: In function 'pam_sm_authenticate':
  pam_faildelay.c:104:34: error: comparison of integer expressions of different signedness: 'long int' and 'unsigned int' [-Werror=sign-compare]
    104 |           if (delay < 0 || delay > UINT_MAX)
        |                                  ^
  pam_faildelay.c:123:32: error: comparison of integer expressions of different signedness: 'long int' and 'unsigned int' [-Werror=sign-compare]
    123 |         if (delay < 0 || delay > UINT_MAX / S_TO_MICROS)
        |                                ^

* modules/pam_faildelay/pam_faildelay.c (pam_sm_authenticate): Cast
"delay" to "unsigned long" in comparisons with unsigned int.

Fixes: dd87776d3683 ("pam_faildelay: validate parameter ranges")