pam_namespace: include stdint.h
pam_namespace.c makes use of SIZE_MAX but doesn't include stdint.h,
resulting in the following build failures on 1.6.0:

  pam_namespace.c: In function 'process_line':
  pam_namespace.c:649:41: error: 'SIZE_MAX' undeclared (first use in this function)
    649 |         if (count > UINT_MAX || count > SIZE_MAX / sizeof(uid_t)) {
        |                                         ^~~~~~~~
  pam_namespace.c:41:1: note: 'SIZE_MAX' is defined in header '<stdint.h>'; did you forget to '#include <stdint.h>'?
     40 | #include "argv_parse.h"
    +++ |+#include <stdint.h>
     41 |
  pam_namespace.c:649:41: note: each undeclared identifier is reported only once for each function it appears in
    649 |         if (count > UINT_MAX || count > SIZE_MAX / sizeof(uid_t)) {
        |                                         ^~~~~~~~

Fixes: v1.6.0~100 ("pam_namespace: validate amount of uids in config")
Resolves: https://github.com/linux-pam/linux-pam/issues/733